aws_region         = "us-east-1"
vpc_cidr           = "10.1.0.0/16"
vpc_name           = "gmedeiros-dev-vpc"
environment        = "Development"
public_subnet_cidr = "10.1.1.0/24"
availability_zone  = "us-east-2a"
project_label      = "gmedeiros"